# Generated by Django 4.0.5 on 2022-07-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_agriculturegoods_delete_myset'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturegoods',
            name='instok',
            field=models.BooleanField(default=True),
        ),
    ]
