# Generated by Django 4.0.5 on 2022-07-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='mobile',
        ),
    ]
