# Generated by Django 4.0.5 on 2022-08-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default='no  token', max_length=100),
        ),
    ]
