# Generated by Django 4.0.5 on 2022-08-03 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_profile_verified_profile_verify_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiondetail', models.TextField()),
                ('coordinationlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.coordinationlist')),
            ],
        ),
    ]
