# Generated by Django 4.0.5 on 2022-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='contact',
            field=models.CharField(default='no  contact', max_length=1000),
        ),
    ]
