# Generated by Django 4.0.5 on 2022-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_rename_coordinationlist_action_coordinationaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturegoods',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='agriculturegoods',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='spacfile'),
        ),
    ]
