# Generated by Django 4.0.5 on 2022-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_agriculturegoods_picture_agriculturegoods_specfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturegoods',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='specfile'),
        ),
    ]
