# Generated by Django 4.0.5 on 2022-08-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_alter_agriculturegoods_specfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
